[package]
name = "fs-manager-tauri"
version = "0.1.0"
description = "fsManager - File System Manager with Tauri"
authors = ["alexIV"]
edition = "2021"

[lib]
name = "fs_manager_tauri_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["protocol-asset"] }
tauri-plugin-shell = "2"
tauri-plugin-fs = "2"
tauri-plugin-dialog = "2"
tauri-plugin-store = "2"
tauri-plugin-updater = "2"
tauri-plugin-process = "2"
tauri-plugin-clipboard-manager = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = "0.4"
notify = "6"
uuid = { version = "1", features = ["v4"] }
pathdiff = "0.2"
dirs = "5"
url = "2"
zip = "0.6"
tokio = { version = "1", features = ["time", "rt", "rt-multi-thread"] }
reqwest = { version = "0.12", features = ["json", "multipart"] }
sha2 = "0.10"
sha1 = "0.10"
md5 = { package = "md-5", version = "0.10" }
