
// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async runScriptInAe(args: RunScriptInAEArgs) : Promise<Result<AEResult, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_script_in_ae", { args }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Tauri-команда: просто запустить AE с готовым jsx-файлом (без ожидания результата)
 */
async launchAeWithScript(aePath: string, scriptPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("launch_ae_with_script", { aePath, scriptPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fsWatchStart(folderPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fs_watch_start", { folderPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fsWatchStop(folderPath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("fs_watch_stop", { folderPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async previewOpen(data: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_open", { data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Подгонка окна под видео + установка aspect-constraint.
 * 
 * Логика (доработка Electron'овской):
 * * Bounds сохраняются под ключом "{type}_{orientation}" — отдельно vertical/
 * horizontal/square. Это решает проблему letterbox'а при переключении между
 * 9:16 и 16:9 видео — каждая ориентация имеет свои сохранённые размеры.
 * * Если для текущей ориентации есть сохранённые bounds — применяем их.
 * Иначе ресайзим под native-размеры видео.
 * * Aspect-constraint (для пользовательского drag-ресайза) ставим всегда.
 */
async previewResize(opts: PreviewResizeOpts) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_resize", { opts }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Стаб: определяет наличие альфа-канала в видео. Реальная реализация требует ffprobe.
 * Пока возвращаем false — Quick Look альфа-channel webm работать не будет, но
 * обычные видео будут проигрываться нормально.
 */
async previewDetectAlpha(filePath: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_detect_alpha", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Стаб: транскодит webm в нужный формат для проигрывания альфа-канала.
 * Возвращает None — frontend упадёт в catch и проиграет оригинал.
 */
async previewTranscodeWebm(filePath: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_transcode_webm", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Стаб: удаляет временный файл после транскодинга.
 */
async previewDeleteTemp(filePath: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("preview_delete_temp", { filePath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async selectFolders(options: SelectFoldersOptions | null) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("select_folders", { options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async selectFiles(options: SelectFilesOptions | null) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("select_files", { options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async copyToClipboard(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copy_to_clipboard", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async showInFolder(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("show_in_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openFileWithDefaultApp(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_file_with_default_app", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createFolder(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_folder", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async renameFile(oldPath: string, newPath: string) : Promise<Result<boolean, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename_file", { oldPath, newPath }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getNodeObjFromFile(path: string) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_node_obj_from_file", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async saveFlowToOptionsFolder(path: string, flow: JsonValue) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_flow_to_options_folder", { path, flow }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPathsFromFiles(paths: string[]) : Promise<Result<string[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_paths_from_files", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async requestDataPreview() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("request_data_preview") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openDevTools() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_dev_tools") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async docsList() : Promise<Result<DocSection[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("docs_list") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async docsRead(sectionName: string, fileName: string) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("docs_read", { sectionName, fileName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Сохранить состояние окна
 */
async saveWindowState(label: string, state: WindowState) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("save_window_state", { label, state }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Загрузить состояние окна
 */
async loadWindowState(label: string) : Promise<Result<WindowState | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("load_window_state", { label }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Список доступных дней архива, отсортированный по убыванию даты (сначала свежие).
 */
async logArchiveListDays() : Promise<Result<ArchiveDay[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("log_archive_list_days") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Читает все лог-группы за указанный день. date — "YYYY-MM-DD".
 */
async logArchiveGetDay(date: string) : Promise<Result<JsonValue[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("log_archive_get_day", { date }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Удаляет архивные файлы старше retentionDays. Возвращает число удалённых файлов.
 */
async logArchiveCleanup() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("log_archive_cleanup") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Полностью очищает архив логов (ручная кнопка). Возвращает число удалённых файлов.
 */
async logArchiveClear() : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("log_archive_clear") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async appSettingsGet() : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("app_settings_get") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async appSettingsSet(settings: JsonValue) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("app_settings_set", { settings }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async appSettingsPatch(patch: JsonValue) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("app_settings_patch", { patch }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async colorTypesGet() : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("color_types_get") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async colorTypesSet(types: JsonValue) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("color_types_set", { types }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Пересканит установленные плагины и обновит список colorTypes:
 * — добавляет новые colorType (которые встречаются в `ui.json#data.colorType`)
 * — помечает orphan: true тем, что больше не используются ни одним плагином
 * — ничего не удаляет (юзер может вернуть плагин обратно)
 * 
 * Порт `electron/main/settings/colorTypes.ts#rescanColorTypes`.
 */
async colorTypesRescan() : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("color_types_rescan") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async colorTypesAdd(name: string, defaultLimit: number | null) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("color_types_add", { name, defaultLimit }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async colorTypesRemove(name: string) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("color_types_remove", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fileTypesGet() : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("file_types_get") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fileTypesSet(types: JsonValue) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("file_types_set", { types }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async programPathsGet() : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("program_paths_get") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async programPathsSet(paths: JsonValue) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("program_paths_set", { paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Автоудаление старых результатов в локальной папке-зеркале.
 * 
 * Структура локальной папки строго фиксирована:
 * localFolder/mainFolderName/projectName/findTime/...
 * 
 * Правила:
 * - `findTime` (уровень 3) — удаляется целиком, если самый свежий файл в её
 * поддереве старше `cleanup.retentionDays`. Возраст считается по
 * max(mtime файлов в поддереве), а не по mtime самой папки — иначе удаление
 * соседей бампало бы mtime родителя.
 * - `projectName` (уровень 2) — удаляется, ТОЛЬКО если после чистки findTime
 * в ней не осталось ни файлов, ни поддиректорий. По возрасту НЕ удаляется.
 * - `mainFolderName` (уровень 1) — то же, что и `projectName`: только если
 * полностью пустая после прохода.
 * 
 * Сами пустые `projectName`/`mainFolderName` создадутся снова при следующем
 * скане, если в источнике появятся новые файлы.
 * 
 * Безопасность вызова: запускать ТОЛЬКО когда очередь обработки пуста и
 * новый скан ещё не стартовал (см. runProcessing.ts). Этот вызов конкурирует
 * с findAllFilesForProcess по тем же путям, и удаление их «из под ног»
 * процессинга и было причиной поломок в Electron-версии.
 */
async cleanupAutoDelete(localFolder: string) : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cleanup_auto_delete", { localFolder }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Стаб для db:registerFound. Реальный online-DB sync не реализован,
 * но фронту нужен **строковый** dbItemId для трекинга item'а в LogWindow и processItem.
 * Возвращаем детерминированный ID на основе pathForDelete + findTime — так чтобы
 * повторный вызов на тот же item дал тот же ID (как и должно быть при идемпотентной регистрации).
 */
async dbRegisterFound(payload: JsonValue) : Promise<Result<string, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("db_register_found", { payload }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

export type AEResult = { success: boolean; data: JsonValue | null; error: string | null }
export type ArchiveDay = { date: string; items: number; bytes: number }
export type DialogFilter = { name: string; extensions: string[] }
export type DocFile = { name: string; fileName: string }
export type DocSection = { name: string; files: DocFile[] }
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type PreviewResizeOpts = { width: number; height: number; aspectRatio?: number | null; extraHeight?: number | null }
export type RunScriptInAEArgs = { 
/**
 * Путь к исполняемому файлу AE (aerender или After Effects.app)
 */
ae_path: string; 
/**
 * Путь к оригинальному JSX-скрипту
 */
script_path: string; 
/**
 * Аргументы, которые попадут в `var inObj = {...}` внутри скрипта
 */
in_obj: JsonValue; 
/**
 * Куда писать временные файлы (tmp dir). По умолчанию — системный temp.
 */
temp_dir: string | null; 
/**
 * Не удалять временные файлы после выполнения
 */
keep_temp_files: boolean | null; 
/**
 * Таймаут ожидания результата в секундах (по умолчанию 120)
 */
timeout_sec: number | null }
export type SelectFilesOptions = { multiSelect?: boolean; filters?: DialogFilter[] | null }
export type SelectFoldersOptions = { multiSelect?: boolean }
export type WindowState = { width: number; height: number; x: number | null; y: number | null; is_maximized: boolean | null }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
